In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler

degerler=np.array([3,78,22,50,45,64])
degerler=degerler.reshape(-1,1)

ss=np.std(degerler)
ortalama=np.mean(degerler)

for i in range(len(degerler)):
    degerler[i]=(degerler[i]-ortalama)/ss

print(degerler)


[[-1]
 [ 1]
 [ 0]
 [ 0]
 [ 0]
 [ 0]]


In [2]:
import numpy as np
from sklearn.preprocessing import StandardScaler

degerler = np.array([3, 78, 22, 50, 45, 64])
degerler = degerler.reshape(-1, 1)

ss = np.std(degerler)
ortalama = np.mean(degerler)
print((degerler[0][0] - ortalama) / ss)

sc = StandardScaler()
print(sc.fit_transform(degerler))


-1.6250784771135995
[[-1.62507848]
 [ 1.37199248]
 [-0.8658205 ]
 [ 0.25308599]
 [ 0.05328126]
 [ 0.81253924]]


In [3]:
import numpy as np
from sklearn.preprocessing import StandardScaler

degerler = np.array([3, 78, 22, 50, 45, 64])
degerler = degerler.reshape(-1,1)

ss = np.std(degerler)
ortalama = np.mean(degerler)

for i in range(6):
    print((degerler[i][0] - ortalama)/ss)

sc = StandardScaler()
print(sc.fit_transform(degerler))


-1.6250784771135995
1.371992484776236
-0.8658205001015079
0.25308599233736395
0.05328126154470828
0.8125392385567999
[[-1.62507848]
 [ 1.37199248]
 [-0.8658205 ]
 [ 0.25308599]
 [ 0.05328126]
 [ 0.81253924]]


In [4]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

degerler = np.array([3, 78, 22, 50, 45, 64])
xmin = np.min(degerler)
xmax = np.max(degerler)

for i in range(6):
    print((degerler[i] - xmin) / (xmax - xmin))

print(MinMaxScaler().fit_transform(degerler.reshape(-1, 1)))


0.0
1.0
0.25333333333333335
0.6266666666666667
0.56
0.8133333333333334
[[0.        ]
 [1.        ]
 [0.25333333]
 [0.62666667]
 [0.56      ]
 [0.81333333]]


In [5]:
from sklearn.preprocessing import RobustScaler
import numpy as np

degerler = np.array([3, 78, 22, 50, 45, 64])
x75 = np.percentile(degerler, 75)
x25 = np.percentile(degerler, 25)
iqr = x75 - x25

print(x75, x25, iqr, np.median(degerler))

olcDeg = (degerler[0] - np.median(degerler)) / iqr
print(olcDeg)

print(RobustScaler().fit_transform(degerler.reshape(-1, 1)))


60.5 27.75 32.75 47.5
-1.3587786259541985
[[-1.35877863]
 [ 0.93129771]
 [-0.77862595]
 [ 0.07633588]
 [-0.07633588]
 [ 0.50381679]]


In [6]:
import numpy as np
from sklearn.preprocessing import Normalizer

# Örnek veri kümesi (2 boyutlu)
veri = np.array([[4, 3, 2, 1],
                 [10, 8, 6, 4],
                 [1, 2, 3, 4]])

# 4. Adım: sklearn kullanarak Normalizer işlemi
normalizer = Normalizer(norm='l2')  # L2 normu kullanılıyor
normalizasyon_sklearn = normalizer.fit_transform(veri)

print("\nsklearn Normalizer Sonucu:\n", normalizasyon_sklearn)



sklearn Normalizer Sonucu:
 [[0.73029674 0.54772256 0.36514837 0.18257419]
 [0.68041382 0.54433105 0.40824829 0.27216553]
 [0.18257419 0.36514837 0.54772256 0.73029674]]


In [7]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder,LabelEncoder,OrdinalEncoder

# Örnek kategorik veri
veri = np.array([['Kırmızı', 'Küçük', 'İlkokul'],
                ['Mavi', 'Orta', 'Lise'],
                ['Yeşil', 'Büyük', 'Üniversite'],
                ['Kırmızı', 'Orta', 'Lise']])

# OneHotEncoder örneği (renk için)
onehot_encoder = OneHotEncoder()
renk_encoded = onehot_encoder.fit_transform(veri[:, 0].reshape(-1, 1)).toarray()

# LabelEncoder örneği (boyut için)
label_encoder = LabelEncoder()
boyut_encoded = label_encoder.fit_transform(veri[:, 1])

# OrdinalEncoder örneği (eğitim seviyesi için)
ordinal_encoder = OrdinalEncoder(categories=[['İlkokul', 'Lise', 'Üniversite']])
egitim_encoded = ordinal_encoder.fit_transform(veri[:, 2].reshape(-1, 1))

print(renk_encoded)
print(boyut_encoded)
print(egitim_encoded)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[1 2 0 2]
[[0.]
 [1.]
 [2.]
 [1.]]
